artifact_location: file:///C:/Users/Hp/Documents/Python Projects/mlops/MLOps_Final_Project/Hand-Gesture-Classification/.mlruns/0
creation_time: 1748645335136
experiment_id: '0'
last_update_time: 1748645335136
lifecycle_stage: active
name: Default
