artifact_uri: file:///C:/Users/Hp/Documents/Python Projects/mlops/MLOps_Final_Project/Hand-Gesture-Classification/.mlruns/200527801718046151/5eb26ad2c655415e91b5c0d280394ad8/artifacts
end_time: 1748645347416
entry_point_name: ''
experiment_id: '200527801718046151'
lifecycle_stage: active
run_id: 5eb26ad2c655415e91b5c0d280394ad8
run_name: LogisticRegression
run_uuid: 5eb26ad2c655415e91b5c0d280394ad8
source_name: ''
source_type: 4
source_version: ''
start_time: 1748645336356
status: 3
tags: []
user_id: Hp
