artifact_location: file:///C:/Users/Hp/Documents/Python Projects/mlops/MLOps_Final_Project/Hand-Gesture-Classification/.mlruns/200527801718046151
creation_time: 1748645335161
experiment_id: '200527801718046151'
last_update_time: 1748645335161
lifecycle_stage: active
name: Hand Gesture Classification
