artifact_uri: file:///C:/Users/Hp/Documents/Python Projects/mlops/MLOps_Final_Project/Hand-Gesture-Classification/.mlruns/200527801718046151/9cb9d8fd2a344ab587cf9c40868728ae/artifacts
end_time: 1748648663197
entry_point_name: ''
experiment_id: '200527801718046151'
lifecycle_stage: active
run_id: 9cb9d8fd2a344ab587cf9c40868728ae
run_name: XGBoost
run_uuid: 9cb9d8fd2a344ab587cf9c40868728ae
source_name: ''
source_type: 4
source_version: ''
start_time: 1748648641468
status: 3
tags: []
user_id: Hp
