artifact_uri: file:///C:/Users/Hp/Documents/Python Projects/mlops/MLOps_Final_Project/Hand-Gesture-Classification/.mlruns/200527801718046151/df7f758ea5644e5ca6c167f02862bde2/artifacts
end_time: 1748645371276
entry_point_name: ''
experiment_id: '200527801718046151'
lifecycle_stage: active
run_id: df7f758ea5644e5ca6c167f02862bde2
run_name: RandomForest
run_uuid: df7f758ea5644e5ca6c167f02862bde2
source_name: ''
source_type: 4
source_version: ''
start_time: 1748645347424
status: 3
tags: []
user_id: Hp
